version: "3.9"
services:
  nginx:
    build:
      context: docker/nginx
    ports:
      - "80:80"

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/app

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/app
